models/Citas.php
<?php

namespace app\models; 

use Yii;

/**
 * This is the model class for table "{{%citas}}".
 *
 * @property int $cit_id_cita 
 * @property string|null $cit_observaciones
 * @property int $cit_id_estatus
 * @property int $cit_servicio
 * @property string $cit_proceso
 * @property string|null $cit_fecha_atencion
 * @property string|null $cit_municipio
 * @property string|null $cit_fecha_registro
 * @property string|null $cit_fecha_modificacion
 * @property int $cit_id_usuaria
 * @property int $cit_id_profesionista
 * @property int $cit_horario
 *
 * @property TipoServicio $citServicio
 * @property Profesionista $citIdProfesionista
 * @property Usuaria $citIdUsuaria
 * @property ConfiguracionHorario $citHorario
 */
class Citas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%citas}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cit_observaciones'], 'string'],
            [['cit_servicio', 'cit_proceso', 'cit_id_usuaria', 'cit_id_profesionista', 'cit_horario'], 'required'],
            [['cit_id_estatus', 'cit_servicio', 'cit_id_usuaria', 'cit_id_profesionista', 'cit_horario'], 'integer'],
            [['cit_fecha_atencion', 'cit_fecha_registro', 'cit_fecha_modificacion'], 'safe'],
            [['cit_proceso'], 'string', 'max' => 50],
            [['cit_municipio'], 'string', 'max' => 25],
            [['cit_id_estatus'], 'default', 'value' => 1],
            [['cit_servicio'], 'exist', 'skipOnError' => true, 'targetClass' => TipoServicio::className(), 'targetAttribute' => ['cit_servicio' => 'serv_id_tipo']],
            [['cit_id_profesionista'], 'exist', 'skipOnError' => true, 'targetClass' => Profesionista::className(), 'targetAttribute' => ['cit_id_profesionista' => 'pro_id']],
            [['cit_id_usuaria'], 'exist', 'skipOnError' => true, 'targetClass' => Usuaria::className(), 'targetAttribute' => ['cit_id_usuaria' => 'reg_id']],
            [['cit_horario'], 'exist', 'skipOnError' => true, 'targetClass' => ConfiguracionHorario::className(), 'targetAttribute' => ['cit_horario' => 'conf_id']],
            [['cit_id_estatus'], 'exist', 'skipOnError' => true, 'targetClass' => Estatus::className(), 'targetAttribute' => ['cit_id_estatus' => 'est_id_estatus']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cit_id_cita' => 'Cita id',
            'cit_observaciones' => 'Observaciones',
            'cit_id_estatus' => 'Estatus',
            'cit_servicio' => 'Servicio',
            'cit_proceso' => 'Proceso',
            'cit_fecha_atencion' => 'Fecha de Atencion',
            'cit_municipio' => 'Municipio',
            'cit_fecha_registro' => 'Fecha de Registro',
            'cit_fecha_modificacion' => 'Fecha de Modificacion',
            'cit_id_usuaria' => 'Usuaria',
            'cit_id_profesionista' => 'Profesionista',
            'cit_horario' => 'Horario',
            'estatus' => 'Estatus',
            'servicio' => 'Servicio',
            'municipio' => 'Municipio',
            'usuaria' => 'Usuaria',
            'horario' => 'Horario',
            'profesionista' => 'Profesionista',
            'profesionistaEspecialidad' => 'Especialidad',
        ];
    }

    /**
     * Gets query for [[CitServicio]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCitServicio()
    {
        return $this->hasOne(TipoServicio::className(), ['serv_id_tipo' => 'cit_servicio']);
    }

    /**
     * Gets query for [[CitIdProfesionista]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCitIdProfesionista()
    {
        return $this->hasOne(Profesionista::className(), ['pro_id' => 'cit_id_profesionista']);
    }

    /**
     * Gets query for [[CitIdUsuaria]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCitIdUsuaria()
    {
        return $this->hasOne(Usuaria::className(), ['reg_id' => 'cit_id_usuaria']);
    }

    /**
     * Gets query for [[CitHorario]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCitHorario()
    {
        return $this->hasOne(ConfiguracionHorario::className(), ['conf_id' => 'cit_horario']);
    }

    public function getCitEstatus()
    {
        return $this->hasOne(Estatus::className(), ['est_id_estatus' => 'cit_id_estatus']);
    }

    public function getCitMunicipio()
    {
        return Municipios::findOne(['efe_key' => '27', 'catalog_key_mun' => $this->cit_municipio]);
    }

    public function getCitUsuaria()
    {
        return $this->hasOne(Usuaria::className(), ['reg_id' => 'cit_id_usuaria']);
    }

    /**
     * Funciones creadas para el modelo 
     **/

    public function getEstatus() 
    {
        return $this->citEstatus->est_nombre;
    }

    public function getServicio()
    {
        return $this->citServicio->serv_nombre;
    }

    public function getMunicipio()
    {
        return $this->citMunicipio->municipio;
    }

    public function getUsuaria()
    {
        return $this->citUsuaria->nombreCompleto;
    }

    public function getHorario()
    {
        return $this->citHorario->conf_descripcion;
    }

    public function getProfesionista()
    {
        return $this->citIdProfesionista->nombreCompleto;
    }

    public function getProfesionistaEspecialidad()
    {
        return $this->citIdProfesionista->especialidad;
    }

    public static function descartados()
    {
        $model = Citas::find()->where(['cit_id_estatus' => 1])->all();
        return sizeof($model);
    }

    public static function sinActualizar()
    {
        $model = Citas::find()->where(['cit_id_estatus' => 2])->all();
        return sizeof($model);
    }

    public static function enProceso()
    {
        $model = Citas::find()->where(['cit_id_estatus' => 3])->all();
        return sizeof($model);
    }

    public static function concluidos()
    {
        $model = Citas::find()->where(['cit_id_estatus' => 4])->all();
        return sizeof($model);
    }
}

controllers/CitasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Citas;
use app\models\CitasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;

use yii\helpers\ArrayHelper;
use app\models\Municipios;
use app\models\Profesionista;
use app\models\Usuaria;
use app\models\ConfiguracionHorario;
use app\models\TipoServicio;
use app\models\Estatus;
use app\models\Dias;
use app\models\AgendaConfiguracion;
use app\models\ConfiguracionProfesionista;
use app\models\HorasAusenciaProfesionista;

/**
 * CitasController implements the CRUD actions for Citas model.
 */
class CitasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        /*return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];*/

        return [
            'ghost-access' => [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ],
        ];
    }

    /**
     * Lists all Citas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CitasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Citas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Citas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($municipio = null, $profesionista = null, $usuaria = null, $proceso = null, $servicio = null, $estatus = null)
    {
        $model = new Citas();
        
        if($municipio != null){$model->cit_municipio = $municipio;}
        if($profesionista != null){$model->cit_id_profesionista = $profesionista;}
        if($usuaria != null){$model->cit_id_usuaria = $usuaria;}
        if($proceso != null){$model->cit_proceso = $proceso;}
        if($servicio != null){$model->cit_servicio = $servicio;}
        if($estatus != null){$model->cit_id_estatus = $estatus;}

        if ($model->load(Yii::$app->request->post())) {
            $model->cit_id_estatus = 1;
            $model->cit_fecha_registro = date("Y-m-d H:i:s");
            $model->cit_fecha_modificacion = date("Y-m-d H:i:s");

            $model->save();

            return $this->redirect(['view', 'id' => $model->cit_id_cita]);
        }

        $municipios = ArrayHelper::map(Municipios::find()->where(['efe_key' => '27'])->all(),'catalog_key_mun','municipio');
        $usuarias = ArrayHelper::map(Usuaria::find()->all(),'reg_id','folioNombreCompleto'); 
        $servicios = ArrayHelper::map(TipoServicio::find()->all(),'serv_id_tipo','serv_nombre');
        $estatus = ArrayHelper::map(Estatus::find()->all(),'est_id_estatus','est_nombre');
        $dias = $this->getDias();//var_dump($dias);die;
        $datesDisabled = $this->getDateDisabled(AgendaConfiguracion::find()->where(['age_status' => 1])->all());
        if($model->cit_id_profesionista !== null){
            $dates = $this->getDateDisabledProfesionista(ConfiguracionProfesionista::find()->where(['con_status' => 2, 'con_todo_el_dia' => 1, 'con_fkProfesionista' => $model->cit_id_profesionista])->all());
            $datesDisabled = array_merge($dates, $datesDisabled);
            //var_dump($datesDisabled);die;
        }
        //var_dump(AgendaConfiguracion::find()->where(['age_status' => 1])->all());die;

        return $this->render('create', [
            'model' => $model,
            'municipios' => $municipios,
            'profesionistas' => $profesionista != null ? ArrayHelper::map(Profesionista::find()->where(['pro_municipio_atencion' => $model->cit_municipio])->all(),'pro_id','nombreCompleto') : [],
            'usuarias' => $usuarias,
            'servicios' => $servicios,
            'estatus' => $estatus,
            'horarios' => [],
            'escenario' => 'create',
            'dias' => $dias,
            'datesDisabled' => $datesDisabled,
            'modelUsuaria' => null,
        ]);
    }

    /**
     * Updates an existing Citas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($municipio = null, $profesionista = null, $usuaria = null, $proceso = null, $servicio = null, $estatus = null, $id)
    {
        $model = $this->findModel($id);

        if($municipio != null){$model->cit_municipio = $municipio;}
        if($profesionista != null){$model->cit_id_profesionista = $profesionista;}
        if($usuaria != null){$model->cit_id_usuaria = $usuaria;}
        if($proceso != null){$model->cit_proceso = $proceso;}
        if($servicio != null){$model->cit_servicio = $servicio;}
        if($estatus != null){$model->cit_id_estatus = $estatus;}

        $modelUsuaria = Usuaria::findOne(['reg_id' => $model->cit_id_usuaria]);//var_dump(Yii::$app->request->post());die;

        if ($model->load(Yii::$app->request->post()) && $modelUsuaria->load(Yii::$app->request->post()) ) {

            $model->cit_fecha_modificacion = date("Y-m-d H:i:s");
            $model->save();

            $modelUsuaria->reg_fecha_modificacion = date("Y-m-d H:i:s");
            $modelUsuaria->save();

            return $this->redirect(['view', 'id' => $model->cit_id_cita]);
        }

        $municipios = ArrayHelper::map(Municipios::find()->where(['efe_key' => '27'])->all(),'catalog_key_mun','municipio');
        $profesionistas = ArrayHelper::map(Profesionista::find()->where(['pro_municipio_atencion' => $model->cit_municipio])->all(),'pro_id','nombreCompleto');
        $usuarias = ArrayHelper::map(Usuaria::find()->all(),'reg_id','folioNombreCompleto');
        $servicios = ArrayHelper::map(TipoServicio::find()->all(),'serv_id_tipo','serv_nombre');
        $estatus = ArrayHelper::map(Estatus::find()->all(),'est_id_estatus','est_nombre');
        $horarios = ArrayHelper::map(ConfiguracionHorario::find()->all(), 'conf_id', 'conf_descripcion');
        $listCitas = ArrayHelper::map(Citas::find()->andWhere(['cit_id_profesionista' => $model->cit_id_profesionista, 'cit_fecha_atencion' => $model->cit_fecha_atencion])->all(),'citHorario.conf_id','citHorario.conf_descripcion');
        $citaHorario = ArrayHelper::map(Citas::find()->andWhere(['cit_id_cita' => $model->cit_id_cita])->all(),'citHorario.conf_id','citHorario.conf_descripcion');
        $dias = $this->getDias();

        $disabledProfesionista =  [];
            
        $configuracionProfesionista = ConfiguracionProfesionista::find()->where(['con_status' => 2, 'con_todo_el_dia' => 0, 'con_fkProfesionista' => $model->cit_id_profesionista])->all();
        foreach ($configuracionProfesionista as $confProfesionista){
            if($this->check_in_range($confProfesionista->con_dia_inicial, $confProfesionista->con_dia_final, $model->cit_fecha_atencion)){
                $arrayProfesionista = ArrayHelper::map(HorasAusenciaProfesionista::find()->where(['hor_fkConfiguracionProfesionista' => $confProfesionista->con_id])->all(), 'horFkConfiguracionHorario.conf_id', 'horFkConfiguracionHorario.conf_descripcion');
                $disabledProfesionista = $disabledProfesionista + $arrayProfesionista;
            }
        }

        $ArrayDisabled = $listCitas + $disabledProfesionista;

        $horarios = array_diff($horarios, $ArrayDisabled);
        $horarios = $horarios + $citaHorario;
        asort($horarios);


        $datesDisabled = $this->getDateDisabled(AgendaConfiguracion::find()->where(['age_status' => 1])->all());

        return $this->render('update', [
            'model' => $model,
            'municipios' => $municipios,
            'profesionistas' => $profesionistas ,
            'usuarias' => $usuarias,
            'servicios' => $servicios,
            'estatus' => $estatus,
            'horarios' => $horarios,
            'escenario' => 'update',
            'dias' => $dias,
            'datesDisabled' => $datesDisabled,
            'modelUsuaria' => $modelUsuaria,
        ]);
    }

    /**
     * Deletes an existing Citas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Citas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Citas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Citas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    //funciones nuevas 
    public function actionProfesionistas() {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $id = end($_POST['depdrop_parents']);
            $list = Profesionista::find()->andWhere(['pro_municipio_atencion' => $id])->asArray()->all();
            $selected  = null;

views/citas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\select2\Select2;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;
use kartik\datecontrol\DateControl;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Citas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="citas-form">

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
            <div class="panel-heading">
                <strong>
                    <span class="glyphicon glyphicon-th"></span> Formulario de Citas
                    <?= Html::a('<i class="glyphicon glyphicon-circle-arrow-left"></i> Regresar', ['index'], ['class' => 'btn btn-sm btn-warning']) ?>
                </strong>
            </div>
            <div class="panel-body">
               <div class="usuaria-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <!-- 
        /Nuevos 
    -->

    <div class="row">
        <div class="col-xs-6">
            <?= $form->field($model, 'cit_municipio')->dropDownList($municipios, [
            'id' => 'fkmunicipio',
            'prompt'=>'Seleccione la entidad ...',
        ]); ?>
        </div>
        <div class="col-xs-6">
            <?= $form->field($model, 'cit_id_profesionista')->widget(DepDrop::classname(), [
                'data' => $profesionistas,
                'options'=>[
                    'id'=>'fkprofesionista',
                    'onchange' => 'redirect(this)'
                ],
                'pluginOptions'=>[
                    'depends'=>['fkmunicipio'],
                    'placeholder'=>'Select...',
                    'url'=>Url::to(['/citas/profesionistas'])
                ],
                /*'pluginEvents' =>[
                    "change" => "function() {redirect();}"
                ],*/
            ]);?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <?= $form->field($model, 'cit_id_usuaria')->widget(Select2::classname(), [
            'data' => $usuarias,
            'options' => [
                'placeholder' => 'Select a state ...',
                'onchange' => 'redirectUsuaria()',
            ],
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ]); ?>
        </div>
        <div class="col-xs-3">
            <?= 
                /*$form->field($model, 'cit_fecha_atencion')->widget(DateControl::classname(), [
                    'type' => 'date',
                    'id' => 'fkfecha',
                    'options'=>['id'=>'fkfecha'],
                    'ajaxConversion' => true,
                    'autoWidget' => true,
                    'widgetClass' => '',
                    'displayFormat' => 'php:d-F-Y',
                    'saveFormat' => 'php:Y-m-d',
                    'saveTimezone' => 'UTC',
                    'displayTimezone' => 'America/Cancun',
                    'widgetOptions' => [
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'php:d-F-Y'
                        ]
                    ],
                    'language' => 'es',
                ]);*/

                /*$form->field($model, 'cit_fecha_atencion')->widget(DatePicker::classname(), [
                    //'name' => 'dp_1',
                    'id' => 'fkfecha',
                    'options'=>['id'=>'fkfecha'],
                    'type' => DatePicker::TYPE_INLINE,
                    //'value' => '23-Feb-1982',
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'yyyy-mm-dd',
                        'daysOfWeekDisabled' => [ 0 , 6 ],
                        'daysOfWeekHighlighted' => $dias,
                        'datesDisabled' => $datesDisabled,
                    ],
                ]);*/

                $form->field($model, 'cit_fecha_atencion')->widget(DatePicker::classname(), [
                    'id' => 'fkfecha',
                    'options'=>['id'=>'fkfecha'],
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'yyyy-mm-dd',
                        'daysOfWeekDisabled' => [ 0 , 6 ],
                        'daysOfWeekHighlighted' => $dias,
                        'datesDisabled' => $datesDisabled,
                    ],
                ]);
            ?>
        </div>

        <div class="col-xs-3">
            <?= 
            
            $form->field($model, 'cit_horario')->widget(DepDrop::classname(), [
                'data' => $horarios,
                'options'=>['id'=>'fkhorario'],
                'pluginOptions'=>[
                    'depends'=>['fkprofesionista', 'fkfecha'],
                    'placeholder'=>'Select...',
                    'url'=>Url::to(['/citas/horarios'])
                ],
                'type'=> DepDrop::TYPE_SELECT2,
            ]);
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-4">
            <?= $form->field($model, 'cit_proceso')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-xs-4">
            <?= $form->field($model, 'cit_servicio')->widget(Select2::classname(), [
            'data' => $servicios,
            'options' => ['placeholder' => 'Select a state ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]); ?>
        </div>
        <?php if($escenario == 'update'){ ?>
        <div class="col-xs-4">
            <?= $form->field($modelUsuaria, 'reg_id_estatus')->widget(Select2::classname(), [
            'data' => $estatus,
            'options' => ['placeholder' => 'Select a state ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]); ?>
        </div>
        <?php } ?>
    </div>
    <?php 
        if($escenario == 'update'){
            echo '<div class="row">';
            echo '<div class="col-xs-12">';
            echo $form->field($model, 'cit_observaciones')->textarea(['rows' => 6]);
            echo '</div></div>';
        }
    ?>

    </div></div></div></div>

    <div class="row">
        <div class="col-md-2 col-md-offset-5">
            <div class="form-group">
                    <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
            </div>

        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
$id = '';
if($escenario == 'update'){
    $id = '&id=' . $model->cit_id_cita;
}

$js = <<< SCRIPT

function redirect(data){
    municipio = $('#fkmunicipio').val();
    usuaria = $('#citas-cit_id_usuaria').val();
    proceso = $('#citas-cit_proceso').val();
    servicio = $('#citas-cit_servicio').val();
    estatus = $('#citas-cit_id_estatus').val();
    if($(data).val() != "") {
        $(location).attr('href','{$escenario}'+'?municipio='+municipio+'&profesionista='+$(data).val()+'&usuaria='+usuaria+'&proceso='+proceso+'&servicio='+servicio+'&estatus='+estatus+'{$id}');
    }
    
}

function redirectUsuaria(){
    profesionista = $('#fkprofesionista').val();
    municipio = $('#fkmunicipio').val();
    usuaria = $('#citas-cit_id_usuaria').val();
    proceso = $('#citas-cit_proceso').val();
    servicio = $('#citas-cit_servicio').val();
    estatus = $('#citas-cit_id_estatus').val();
    if(usuaria != "") {
        $(location).attr('href','{$escenario}'+'?municipio='+municipio+'&profesionista='+profesionista+'&usuaria='+usuaria+'&proceso='+proceso+'&servicio='+servicio+'&estatus='+estatus+'{$id}');
    }
    //alert(profesionista);
}

SCRIPT;

$this->registerJs($js, $this::POS_END);
?>

views/citas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CitasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="citas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'cit_id_cita') ?>

    <?= $form->field($model, 'cit_observaciones') ?>

    <?= $form->field($model, 'cit_id_estatus') ?>

    <?= $form->field($model, 'cit_servicio') ?>

    <?= $form->field($model, 'cit_proceso') ?>

    <?php // echo $form->field($model, 'cit_fecha_atencion') ?>

    <?php // echo $form->field($model, 'cit_municipio') ?>

    <?php // echo $form->field($model, 'cit_fecha_registro') ?>

    <?php // echo $form->field($model, 'cit_fecha_modificacion') ?>

    <?php // echo $form->field($model, 'cit_id_usuaria') ?>

    <?php // echo $form->field($model, 'cit_id_profesionista') ?>

    <?php // echo $form->field($model, 'cit_horario') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/citas/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Citas */

$this->title = 'Create Citas';
$this->params['breadcrumbs'][] = ['label' => 'Citas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="citas-create">

    <?= $this->render('_form', [
        'model' => $model,
        'municipios' => $municipios,
        'profesionistas' => $profesionistas,
        'usuarias' => $usuarias,
        'servicios' => $servicios,
        'estatus' => $estatus,
        'horarios' => $horarios,
        'escenario' => $escenario,
        'dias' => $dias,
        'datesDisabled' => $datesDisabled,
        'modelUsuaria' => $modelUsuaria,
    ]) ?>

</div>

views/citas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Citas */

$this->title = 'Update Citas: ' . $model->cit_id_cita;
$this->params['breadcrumbs'][] = ['label' => 'Citas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->cit_id_cita, 'url' => ['view', 'id' => $model->cit_id_cita]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="citas-update">

    <?= $this->render('_form', [
        'model' => $model,
        'municipios' => $municipios,
        'profesionistas' => $profesionistas,
        'usuarias' => $usuarias,
        'servicios' => $servicios,
        'estatus' => $estatus,
        'horarios' => $horarios,
        'escenario' => $escenario,
        'dias' => $dias,
        'datesDisabled' => $datesDisabled,
        'modelUsuaria' => $modelUsuaria,
    ]) ?>

</div>